In [11]:
import pandas as pd
import numpy as np

In [12]:
data=pd.read_csv('wiki_movie_plots_deduped.csv')

In [13]:
data.head()

Release Year                             Title Origin/Ethnicity  \
0          1901            Kansas Saloon Smashers         American   
1          1901     Love by the Light of the Moon         American   
2          1901           The Martyred Presidents         American   
3          1901  Terrible Teddy, the Grizzly King         American   
4          1902            Jack and the Beanstalk         American   

                             Director Cast    Genre  \
0                             Unknown  NaN  unknown   
1                             Unknown  NaN  unknown   
2                             Unknown  NaN  unknown   
3                             Unknown  NaN  unknown   
4  George S. Fleming, Edwin S. Porter  NaN  unknown   

                                           Wiki Page  \
0  https://en.wikipedia.org/wiki/Kansas_Saloon_Sm...   
1  https://en.wikipedia.org/wiki/Love_by_the_Ligh...   
2  https://en.wikipedia.org/wiki/The_Martyred_Pre...   
3  https://en.wikipedia.org/wiki/Terrible_Teddy,_...   
4  https://en.wikipedia.org/wiki/Jack_and_the_Bea...   

                                                Plot  
0  A bartender is working at a saloon, serving dr...  
1  The moon, painted with a smiling face hangs ov...  
2  The film, just over a minute long, is composed...  
3  Lasting just 61 seconds and consisting of two ...  
4  The earliest known adaptation of the classic f...

In [14]:
data.shape


(34886, 8)

List of available movies of different orign

In [15]:
np.unique(data['Origin/Ethnicity'])

array(['American', 'Assamese', 'Australian', 'Bangladeshi', 'Bengali',
       'Bollywood', 'British', 'Canadian', 'Chinese', 'Egyptian',
       'Filipino', 'Hong Kong', 'Japanese', 'Kannada', 'Malayalam',
       'Malaysian', 'Maldivian', 'Marathi', 'Punjabi', 'Russian',
       'South_Korean', 'Tamil', 'Telugu', 'Turkish'], dtype=object)

Selecting the movies origin and release date 

In [16]:
data2=data.loc[(data['Origin/Ethnicity']=='American')|( data['Origin/Ethnicity']== 'Australian')|( data['Origin/Ethnicity']=='Bollywood')|(data['Origin/Ethnicity']=='British')|(data['Origin/Ethnicity']== 'Canadian') & (data['Release Year']>2000)]

In [17]:
my_data=pd.DataFrame(data2)

In [18]:
my_data

Release Year                             Title Origin/Ethnicity  \
0              1901            Kansas Saloon Smashers         American   
1              1901     Love by the Light of the Moon         American   
2              1901           The Martyred Presidents         American   
3              1901  Terrible Teddy, the Grizzly King         American   
4              1902            Jack and the Beanstalk         American   
...             ...                               ...              ...   
27123          2017                        Kadvi Hawa        Bollywood   
27124          2017                     Rajiv Dhingra        Bollywood   
27125          2017                    Fukrey Returns        Bollywood   
27126          2017                  Monsoon Shootout        Bollywood   
27127          2017                   Tiger Zinda Hai        Bollywood   

                                              Director  \
0                                              Unknown   
1                                              Unknown   
2                                              Unknown   
3                                              Unknown   
4                   George S. Fleming, Edwin S. Porter   
...                                                ...   
27123                                Nila Madhab Panda   
27124  Kapil Sharma, Varun Badola & Edward Sonnenblick   
27125                            Mrighdeep Singh Lamba   
27126                                       Amit Kumar   
27127                                  Ali Abbas Zafar   

                                                    Cast           Genre  \
0                                                    NaN         unknown   
1                                                    NaN         unknown   
2                                                    NaN         unknown   
3                                                    NaN         unknown   
4                                                    NaN         unknown   
...                                                  ...             ...   
27123  Sanjay Mishra, Ranvir Shorey, Tillotama Shome,...  drama/disaster   
27124                                             Comedy        k9 films   
27125          Pulkit Samrat, Priya Anand & Varun Sharma          comedy   
27126  Nawazuddin Siddiqui, Vijay Varma & Tannishtha ...  crime/thriller   
27127                         Salman Khan & Katrina Kaif    action/drama   

                                               Wiki Page  \
0      https://en.wikipedia.org/wiki/Kansas_Saloon_Sm...   
1      https://en.wikipedia.org/wiki/Love_by_the_Ligh...   
2      https://en.wikipedia.org/wiki/The_Martyred_Pre...   
3      https://en.wikipedia.org/wiki/Terrible_Teddy,_...   
4      https://en.wikipedia.org/wiki/Jack_and_the_Bea...   
...                                                  ...   
27123           https://en.wikipedia.org/wiki/Kadvi_Hawa   
27124              https://en.wikipedia.org/wiki/Firangi   
27125       https://en.wikipedia.org/wiki/Fukrey_Returns   
27126     https://en.wikipedia.org/wiki/Monsoon_Shootout   
27127      https://en.wikipedia.org/wiki/Tiger_Zinda_Hai   

                                                    Plot  
0      A bartender is working at a saloon, serving dr...  
1      The moon, painted with a smiling face hangs ov...  
2      The film, just over a minute long, is composed...  
3      Lasting just 61 seconds and consisting of two ...  
4      The earliest known adaptation of the classic f...  
...                                                  ...  
27123  The film is based on true stories from drought...  
27124  In the 1920s, Manga (Kapil Sharma) is an unedu...  
27125  After their admission in college, Hunny, Chooc...  
27126  As the raging monsoon lashes Mumbai, the comme...  
27127  During a dark night in Iraq, an American journ...  

[24976 rows x 8 columns]

Eliminating all unnecessary columns and only keeping Title and Plot of the movie

In [19]:
finaldata=my_data[['Title','Plot']]
finaldata=finaldata.set_index('Title')
finaldata.head(50)

Plot
Title                                                                                               
Kansas Saloon Smashers                             A bartender is working at a saloon, serving dr...
Love by the Light of the Moon                      The moon, painted with a smiling face hangs ov...
The Martyred Presidents                            The film, just over a minute long, is composed...
Terrible Teddy, the Grizzly King                   Lasting just 61 seconds and consisting of two ...
Jack and the Beanstalk                             The earliest known adaptation of the classic f...
Alice in Wonderland                                Alice follows a large white rabbit down a "Rab...
The Great Train Robbery                            The film opens with two bandits breaking into ...
The Suburbanite                                    The film is about a family who move to the sub...
The Little Train Robbery                           The opening scene shows the interior of the ro...
The Night Before Christmas                         Scenes are introduced using lines of the poem....
Dream of a Rarebit Fiend                           The Rarebit Fiend gorges on Welsh rarebit at a...
From Leadville to Aspen: A Hold-Up in the Rockies  The film features a train traveling through th...
Kathleen Mavourneen                                Irish villager Kathleen is a tenant of Captain...
Daniel Boone                                       Boone's daughter befriends an Indian maiden as...
How Brown Saw the Baseball Game                    Before heading out to a baseball game at a nea...
Laughing Gas                                       The plot is that of a black woman going to the...
The Adventures of Dollie                           On a beautiful summer day a father and mother ...
The Black Viper                                    A thug accosts a girl as she leaves her workpl...
A Calamitous Elopement                             A young couple decides to elope after being ca...
The Call of the Wild                               A white girl (Florence Lawrence) rejects a pro...
A Christmas Carol                                  No prints of the first American film adaptatio...
The Fight for Freedom                              The film opens in a town on the Mexican border...
At the Altar                                       A rejected admirer sets up a trap to kill his ...
A Drunkard's Reformation                           John Wharton, the husband of a true and trusti...
The Golden Louis                                   An old woman sends a girl begging in the stree...
The Lure of the Gown                               The story as told by Moving Picture World read...
An Arcadian Maid                                   Mary Pickford plays Priscilla an unemployed ma...
A Christmas Carol                                  The day before Christmas, Ebenezer Scrooge ref...
Frankenstein                                       Described as "a liberal adaptation of Mrs. She...
Hemlock Hoax, the Detective                        Hemlock Hoax is a detective who has little res...
The House with Closed Shutters                     During the American Civil War a young soldier ...
A Lad from Old Ireland                             An Irish boy (Olcott) emigrates to America to ...
Pocahontas                                         Though the film is presumed lost, a synopsis s...
Ramona                                             Ramona chronicles the romance between Ramona (...
What the Daisy Said                                The film opens upon two sisters (Martha, playe...
The Wonderful Wizard of Oz                         In Kansas, Dorothy and Imogene the cow are cha...
Baseball and Bloomers                              Though the film is presumed lost, a synopsis s...
The Black Arrow: A Tale of the Two Roses           The novel is set in the reign of "old King Hen...
Brown of Harvard                                   The s

In [20]:
finaldata['Plot']['Thor']

'In 965 AD, Odin, king of Asgard, wages war against the Frost Giants of Jotunheim and their leader Laufey, to prevent them from conquering the nine realms, starting with Earth. The Asgardian warriors defeat the Frost Giants and seize the source of their power, the Casket of Ancient Winters.\r\nIn the present,[N 2] Odin\'s son Thor prepares to ascend to the throne of Asgard, but is interrupted when Frost Giants attempt to retrieve the Casket. Against Odin\'s order, Thor travels to Jotunheim to confront Laufey, accompanied by his brother Loki, childhood friend Sif and the Warriors Three: Volstagg, Fandral, and Hogun. A battle ensues until Odin intervenes to save the Asgardians, destroying the fragile truce between the two races. For Thor\'s arrogance, Odin strips his son of his godly power and exiles him to Earth as a mortal, accompanied by his hammer Mjölnir, now protected by an enchantment that allows only the worthy to wield it.\r\nThor lands in New Mexico, where astrophysicist Dr. Ja


# Preprocess the data Remove Stopwords and Lemmatize

In [21]:
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\zenis\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\zenis\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\zenis\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\zenis\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [22]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords


In [23]:
lemmatizer=WordNetLemmatizer()

In [24]:
def preprocess_sentences(text):
    text = text.lower()
    words = nltk.word_tokenize(text)
    my_sent=[lemmatizer.lemmatize(word) for word in words if word not in stopwords.words('english')]
    finalsent = ' '.join(my_sent)

    finalsent = finalsent.replace("n't", " not")
    finalsent = finalsent.replace("'m", " am")
    finalsent = finalsent.replace("'s", " is")
    finalsent = finalsent.replace("'re", " are")
    finalsent = finalsent.replace("'ll", " will")
    finalsent = finalsent.replace("'ve", " have")
    finalsent = finalsent.replace("'d", " would")
    
    return finalsent

In [25]:
finaldata['new_plot']=finaldata['Plot'].apply(preprocess_sentences)

In [28]:
finaldata.head()

Plot  \
Title                                                                                 
Kansas Saloon Smashers            A bartender is working at a saloon, serving dr...   
Love by the Light of the Moon     The moon, painted with a smiling face hangs ov...   
The Martyred Presidents           The film, just over a minute long, is composed...   
Terrible Teddy, the Grizzly King  Lasting just 61 seconds and consisting of two ...   
Jack and the Beanstalk            The earliest known adaptation of the classic f...   

                                                                           new_plot  
Title                                                                                
Kansas Saloon Smashers            bartender working saloon , serving drink custo...  
Love by the Light of the Moon     moon , painted smiling face hang park night . ...  
The Martyred Presidents           film , minute long , composed two shot . first...  
Terrible Teddy, the Grizzly King  lasting 61 second consisting two shot , first ...  
Jack and the Beanstalk            earliest known adaptation classic fairytale , ...

# Using TF-IDF to vectorize preprocessed movie plots

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
tfidf_movieid=tfidf.fit_transform((finaldata['new_plot']))



In [30]:
#finding cosine similarity between vectors
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(tfidf_movieid,tfidf_movieid)

In [46]:
print(similarity)

[[1.         0.03373584 0.00731814 ... 0.00888072 0.         0.00300821]
 [0.03373584 1.         0.00721289 ... 0.01053932 0.0013548  0.00410898]
 [0.00731814 0.00721289 1.         ... 0.         0.00498507 0.01718891]
 ...
 [0.00888072 0.01053932 0.         ... 1.         0.01358463 0.06911689]
 [0.         0.0013548  0.00498507 ... 0.01358463 1.         0.0061194 ]
 [0.00300821 0.00410898 0.01718891 ... 0.06911689 0.0061194  1.        ]]


In [31]:
indices=pd.Series(finaldata.index)

In [32]:
indices

0                  Kansas Saloon Smashers
1           Love by the Light of the Moon
2                 The Martyred Presidents
3        Terrible Teddy, the Grizzly King
4                  Jack and the Beanstalk
                       ...               
24971                          Kadvi Hawa
24972                       Rajiv Dhingra
24973                      Fukrey Returns
24974                    Monsoon Shootout
24975                     Tiger Zinda Hai
Name: Title, Length: 24976, dtype: object

In [33]:
def recommendations(title, cosine_sim = similarity):
  try:
    index = indices[indices == title].index[0]
    print(index)
    similarity_scores = pd.Series(cosine_sim[index]).sort_values(ascending = False)
    print(similarity_scores)
    top_10_movies = list(similarity_scores.iloc[1:11].index)
    print(top_10_movies)
    recommended_movies = [list(finaldata.index)[i] for i in top_10_movies]
    return recommended_movies
  except:
    print("No movie name found")  

In [34]:
recommendations("Thor")

16130
16130    1.000000
17340    0.576967
16697    0.537255
14762    0.404941
16178    0.401017
           ...   
22948    0.000000
19534    0.000000
13376    0.000000
18416    0.000000
8067     0.000000
Length: 24976, dtype: float64
[17340, 16697, 14762, 16178, 13916, 12613, 10985, 16648, 12459, 7290]


['Thor: Ragnarok',
 'Thor: The Dark World',
 'Son of the Mask',
 'Avengers, TheThe Avengers',
 ' O',
 'Bad Moon',
 'The Incredible Hulk Returns',
 'Prisoners',
 'The Hills Have Eyes III',
 'Teenagers from Outer Space']

In [36]:
recommendations("Ice Age")

14074
14074    1.000000
14959    0.621496
15663    0.523612
16302    0.356967
6695     0.351052
           ...   
2184     0.000000
24530    0.000000
18988    0.000000
24524    0.000000
23009    0.000000
Length: 24976, dtype: float64
[14959, 15663, 16302, 6695, 19925, 17113, 10439, 12166, 9915, 20373]


['Ice Age: The Meltdown',
 'Ice Age: Dawn of the Dinosaurs',
 'Ice Age: Continental Drift',
 'The Wrong Man',
 'The Buttercup Chain',
 'Ice Age: Collision Course',
 'Runaway Train',
 'Corrina, Corrina',
 'Zorro, the Gay Blade',
 'Sid and Nancy']

In [43]:
recommendations("Tiger Zinda Hai")

24975
24975    1.000000
24686    0.571575
2085     0.273579
8714     0.272924
14002    0.262851
           ...   
22233    0.000000
18068    0.000000
18067    0.000000
11046    0.000000
23746    0.000000
Length: 24976, dtype: float64
[24686, 2085, 8714, 14002, 873, 3929, 23448, 24748, 24342, 7925]


['Ek Tha Tiger',
 'The Jungle Princess',
 'Pretty Maids All in a Row',
 'Below',
 'Where East is East',
 'The Tiger Woman',
 'Hum',
 'Raanjhanaa',
 'Jannat',
 'A Tiger Walks']

In [44]:
import pickle

In [45]:
pickle.dump(finaldata,open('movies.pkl','wb'))

In [47]:
pickle.dump(similarity,open('similarity.pkl','wb'))